### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by QuintinSmith** [TeamSpeak-Systems/ts3_sdk_dotNet#3]
I am not receiving any audio from the ts c# sdk for xamarin android

**Comment by muenchow** [comment]
Hi, the current sdk does not contain a sound backend for android. only the current beta sdk for c has that backend. http://dl.4players.de/ts/releases/pre_releases/sdk/ts3_sdk_3.0.4.4-Beta-2.zip
In order to make it work with c# you have to include the android binary and soundbackend from that beta sdk.
